# Generated by Django 5.0.7 on 2024-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keen_app', '0006_address_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagevarient',
            name='img',
            field=models.URLField(max_length=700),
        ),
    ]
