# Generated by Django 5.0.6 on 2024-07-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keen_app.category')),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keen_app.colorvariant')),
                ('size_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keen_app.sizevariant')),
            ],
        ),
        migrations.CreateModel(
            name='ImageVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images_')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keen_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Buy_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('product_buy', models.BooleanField(default=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keen_app.product')),
            ],
        ),
    ]
